### ISSUE TITLE
--folder <name> Run requests within a particular folder/folders 

### ISSUE THREAD

**Issue by petrisorionel** [nareshnavinash/newman-run#2]
Run requests within a particular folder/folders or specific requests in a collection. Multiple folders or requests can be specified by using --folder multiple times, like so: --folder f1 --folder f2 --folder r1 --folder r2.

**Comment by nareshnavinash** [comment]
@petrisorionel Let me know whether I have understood your requirement correctly,

You have multiple folders like,

| - Root_folder
        | - Folder_1
                | - Collections
                | - Feed file required by Newman-run
        | - Folder_2
                | - Collections
                | - Feed file required by Newman-run
        | - Folder_3
                | - Collections
                | - Feed file required by Newman-run

And you are expecting this package to run in the root directory by mentioning the folder like `--folder f1 --folder f2 --folder r1 --folder r2`. As you may know, newman-run requires a feed file as a mandatory input to run multiple collections in a single run assuming that each subfolder has the feed file in it so that newman-run parse the feed file and run multiple folder collections?

Can I also know the real-time use-case where we would face this situation?

**Comment by petrisorionel** [comment]
newman offer the possibility to run a specific folder from a collection, see https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/

it will be great if we can add that option in feed file, something like this

`
{
    "runs":[
        {
            "collection": "./collections/test_scripts.postman_collection.json",
“folder”: “specific folder that belongs to test_scripts.postman_collection.json”
        },
        {
            "collection": "./collections/file_upload_collection.postman_collection.json",
            "environment": "./environment/test_environment.json",
“folder”: “specific folder that belongs to file_upload_collection.postman_collection.json”
        }
        
    ]
}
`

**Comment by nareshnavinash** [comment]
@petrisorionel sorry for being late on the reply, so let me know if I understand the requirement correctly. So I have multiple collections which I am trying to run via `newman-run` and in that collections, I need to run specific folders by mentioning in the feed file?

**Comment by nareshnavinash** [comment]
Since its been a long time, closing this Issue.
